### PR TITLE
modify readme for organizing repo

### PR DESCRIPTION
**Pull request by PiotrNewt**
### What problem does this PR solve?

it is my pleasure to tell everybody that we organize this rope for more clear,  so it's easy for more database enthusiast to join this reference course, and have fun!
- we privately owned a repo for the students in our laboratory, it's also good for other people reading this repo
- we will 'cherry-pick' the good homework to this repo as a reference
- we will also 'cherry-pick' what you contribute from this repo to the private ones, thx
- we will continue to improve this repo, for now, we will add more Further Reading

looking forward to your contribution!!

### What have you done or changed in this PR?
- delete some homework
- modify 'readme.md', add some link of knowledge point

### What test did you complete before submitting the PR?
- none

### CODE REVIEW

**Review by ehds — COMMENTED** [review]
为什么删除了 week1 的实验报告？

**Comment by PiotrNewt** [comment]
> 为什么删除了 week1 的实验报告？

考虑作为公开库的参考，所以只留下了 week1 的优秀报告；
后面每周都一样的操作，提高整个 repo 可读性。（且所有作业在私有库都有留存）
何如？

**Comment by ehds** [comment]
LGTM

**Review by karmanluo — APPROVED** [review]
LGTM

**Review by ehds — APPROVED** [review]

**Pull request merged**
